name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  e2e-tests:
    name: E2E Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run Mock API
        run: npm run api:e2e &

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
